### ISSUE TITLE
Templates plugin not working on webpack installation of ckeditor 

### ISSUE THREAD

**Issue by drososanastasios** [FriendsOfSymfony/FOSCKEditorBundle#185]
### Environment
Symfony 4.2
#### Symfony packages
friendsofsymfony/ckeditor-bundle: 2.1.0,

I started a fresh symfony flex project and I installed webpack based on documentation. What I did next is that I followed the documentation in order to install ckeditor bundle based on:

https://symfony.com/doc/master/bundles/FOSCKEditorBundle/installation.html

Since I try to migrate from symfony 3.4 to symfony 4 I used the same configuration as before that contains templates. Without the templates everything works as expected.
## Steps to reproduce
Add a simple configuration that contain templates:
```
badge_config:
            toolbar: "custom_toolbar"
            filebrowserBrowseRoute: 'elfinder'
            filebrowserBrowseRouteParameters: []
            extraPlugins: 'templates'
            templates: 'badge_templates'
templates:
        badge_templates:
            templates:
                - title: '1x1 C'
                  template: 'ckeditor_templates/badges/badge1x1C.html.twig'
                - title: '2x1 CC'
                  template: 'ckeditor_templates/badges/badge2x1CC.html.twig'
```
## Expected results
An editor that contains the templates.
## Actual results
The editor is shown as simple text. In console.log I see that:
```
Uncaught TypeError: CKEDITOR.addTemplates is not a function
```
