### ISSUE TITLE
Mathjx support

### ISSUE THREAD

**Issue by napestershine** [FriendsOfSymfony/FOSCKEditorBundle#197]
How can I use Mathjax https://ckeditor.com/cke4/addon/mathjax, in FOSCkeditor ?

Thanks

**Comment by Julen10** [comment]
You have to download the zip, unzip it into public/bundles/fosckeditor/plugins/ and change the config/packages/fos_ckeditor.yml adding this:
```
fos_ckeditor:
    default_config: simple_config
        configs:
            simple_config:
                extraPlugins:
                    - 'mathjax'
             plugins:
                mathjax:
                    path: 'bundles/fosckeditor/plugins/mathjax/'
                    filename: 'plugin.js'
```

**Comment by napestershine** [comment]
Hi @Julen10 

here is my config:

```
fos_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            extraPlugins:
                - 'mathjax'
            plugin:
                mathjx:
                    path: 'bundles/fosckeditor/plugins/mathjax/'
                    filename: 'plugin.js'

```

is it right?

Thanks

**Comment by napestershine** [comment]
![image](https://user-images.githubusercontent.com/8603325/62848117-39cadf80-bcda-11e9-80a4-a8bf33fac80c.png)

**Comment by Julen10** [comment]
@napestershine i have made a mistake, here is how your config should look like:
```
fos_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            extraPlugins:
                - 'mathjax'
    plugins:
        mathjx:
            path: 'bundles/fosckeditor/plugins/mathjax/'
            filename: 'plugin.js'
```

You should change:
 - Put 's' on plugin --> plugins
 - Put the correct indentation on plugins: and following lies
 - I´m not sure if the path should start with slash or not ('**/**bundles/fos...' or 'bundles/fos..')
