### ISSUE TITLE
Error changing plugin path

### ISSUE THREAD

**Issue by Julen10** [FriendsOfSymfony/FOSCKEditorBundle#199]
### Environment
Symfony 4.2.8 
#### Symfony packages

```
$ composer show --latest 'symfony/*'
```
Symfony flex ones

## Subject

I can´t change the plugin path, it just takes the default path

## Steps to reproduce

Install plugin and add this:
```
fos_ck_editor:
    default_config: simple_config
    configs:
        simple_config:
            extraPlugins:
                - 'wordcount'
                - 'notification'
        plugins:
            wordcount:
                path: 'fosckeditor/plugins/wordcount/'
                filename: 'plugin.js'
            notification:
                path: 'fosckeditor/plugins/notification/'
                filename: 'plugin.js'
```

## Expected results

The plugin changes from `localhost:8080/bundles/fosckeditor/plugins/wordcount/plugin.js` to `localhost:8080/fosckeditor/plugins/wordcount/plugin.js`

## Actual results

![imagen](https://user-images.githubusercontent.com/17271582/62628020-d41dd280-b92a-11e9-8b0b-a60ac1f1d7c2.png)
