### ISSUE TITLE
When adding additional config i get a JS code but it does work

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSCKEditorBundle#247]
When i have additional config like:
```yaml
fos_ck_editor:
  default_config: my_config
  configs:
    my_config:
      language: nl
      extraPlugins:
        - 'autogrow'
        - 'youtube'
        - 'wordcount'
      autoGrow_minHeight: 500
      autoGrow_maxHeight: 500
      autoGrow_onStartup: true
```

I get the following JS error when rendering the template:
```
VM1727 ckeditor.js:19 [CKEDITOR] Error code: editor-element-conflict. {editorName: 'x'}
(anonymous) @ VM1727 ckeditor.js:19
h @ VM1727 ckeditor.js:10
(anonymous) @ VM1727 ckeditor.js:11
window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.error @ VM1727 ckeditor.js:18
CKEDITOR.editor._getEditorElement @ VM1727 ckeditor.js:280
a @ VM1727 ckeditor.js:340
CKEDITOR.replace @ VM1727 ckeditor.js:345
CKEDITOR.replaceAll @ VM1727 ckeditor.js:346
(anonymous) @ VM1727 ckeditor.js:349
b @ VM1727 ckeditor.js:7
a @ VM1727 ckeditor.js:7
VM1727 ckeditor.js:19 [CKEDITOR] For more information about this error go to https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#editor-element-conflict
```

But the editor renders correctly.

When i enabled jQuery it worked i got the suggestion by looking at second answer  https://stackoverflow.com/questions/59158795/ckeditor-error-code-editor-element-conflict
