### ISSUE TITLE
"Error code: exportpdf-no-token-url" or how we can remove plugin via configuration?

### ISSUE THREAD

**Issue by indapublic** [FriendsOfSymfony/FOSCKEditorBundle#248]
Hi, beautiful people!

```
"friendsofsymfony/ckeditor-bundle": "^2.4"
```

```
fos_ck_editor:
    default_config: basic
    configs:
        basic:
            toolbar: basic
```

On page load with integrated ckeditor I see this warning:

```
[CKEDITOR] Error code: exportpdf-no-token-url.
https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#exportpdf-no-token-url
```

Yes, it's not a blocker but I want to avoid it anyway.

Regarding to Internet we should to use `removePlugins` property ([Link #1](https://www.devmaesters.com/blog/thread/1), [Link #2](https://stackoverflow.com/questions/68318056/django-ckeditor-error-code-exportpdf-no-token-url)), but seems like this bundles doesn't support it

Thank you.

**Comment by jorrit** [comment]
Just do this:

```
fos_ck_editor:
    default_config: basic
    configs:
        basic:
            toolbar: basic
            removePlugins: 'exportpdf'
```
