### ISSUE TITLE
code snippet is non-existent

### ISSUE THREAD

**Issue by pprgva** [FriendsOfSymfony/FOSCKEditorBundle#249]
### Environment
Symfony 6.1.12

#### Symfony packages

```
"php": ">=8.1",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "doctrine/annotations": "^1.0",
        "doctrine/doctrine-bundle": "^2.8",
        "doctrine/doctrine-migrations-bundle": "^3.2",
        "doctrine/orm": "^2.14",
        "friendsofsymfony/ckeditor-bundle": "^2.4",
        "phpdocumentor/reflection-docblock": "^5.3",
        "phpstan/phpdoc-parser": "^1.16",
        "sensio/framework-extra-bundle": "^6.1",
        "symfony/asset": "6.1.*",
        "symfony/console": "6.1.*",
        "symfony/doctrine-messenger": "6.1.*",
        "symfony/dotenv": "6.1.*",
        "symfony/expression-language": "6.1.*",
        "symfony/flex": "^2",
        "symfony/form": "6.1.*",
        "symfony/framework-bundle": "6.1.*",
        "symfony/http-client": "6.1.*",
        "symfony/intl": "6.1.*",
        "symfony/mailer": "6.1.*",
        "symfony/mime": "6.1.*",
        "symfony/monolog-bundle": "^3.0",
        "symfony/notifier": "6.1.*",
        "symfony/process": "6.1.*",
        "symfony/property-access": "6.1.*",
        "symfony/property-info": "6.1.*",
        "symfony/runtime": "6.1.*",
        "symfony/security-bundle": "6.1.*",
        "symfony/serializer": "6.1.*",
        "symfony/string": "6.1.*",
        "symfony/translation": "6.1.*",
        "symfony/twig-bundle": "6.1.*",
        "symfony/validator": "6.1.*",
        "symfony/web-link": "6.1.*",
        "symfony/webpack-encore-bundle": "^1.16",
        "symfony/yaml": "6.1.*",
        "twig/extra-bundle": "^2.12|^3.0",
        "twig/twig": "^2.12|^3.0"
```

## Subject
Despite the presence of the codenippet plugin, it remains invisible in the menu

## Steps to reproduce
Nothing more than the installation: https://symfony.com/bundles/FOSCKEditorBundle/current/installation.html

        main_config:
            height: 230
            width: 1500 
            toolbar: full
## Expected results
<img width="80" alt="Capture d’écran 2023-02-13 à 13 30 12" src="https://user-images.githubusercontent.com/5247838/218458031-6f215b60-f920-4dbf-b654-e715b373c661.png">

.. this one more

## Actual results

<img width="1085" alt="Capture d’écran 2023-02-13 à 13 24 49" src="https://user-images.githubusercontent.com/5247838/218456980-3b4c3c24-83ae-4f48-abff-8704014f8f22.png">

**Comment by khaledBou** [comment]
I already have the same problem, i installed manually codesnippet inside plugins folder and inside config file iadded this : 

```
`fos_ck_editor:
  configs:
    main_config:
      extraPlugins: "codesnippet"
      toolbar:
        - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike', 'Blockquote', '-', 'Link', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Image', 'Table', '-', 'Styles', 'Format','Font','FontSize', '-', 'TextColor', 'BGColor', 'Source', 'codeSnippet'] }
  plugins:
    codesnippet:
      path: "/bundles/fosckeditor/plugins/codesnippet/" # with trailing slash
      filename: "plugin.js"`
```

I don't understand why fos ckeditor doesn't contain codesnippet plugin by defaut !
